### PR TITLE
WIP: Move to enum-based commands

### PR DESCRIPTION
**Pull request by Herbstein**
Exploration of needed changes for #74.

Biggest needs right now is handling default command behavior and the command line - both are completely disabled at this time.

### CODE REVIEW

**Comment by Herbstein** [comment]
Everything here is subject to change. I have basically pulled out the old commands into enums. 

Some of the commands, like the `Move` and `Shift` commands, have two parameters but a "strong" default. I represented those second parameters with `Option<T>` types, but that quickly becomes unwieldy. Another way I imagined doing this was having the associated `-Mode` enum have both a `Down` and a `Down5` element - but that is even less ergonomic.

Not entirely sure if we should just leave them as they are now, or what the right change is.

**Comment by Herbstein** [comment]
The biggest problem with implementing the default command behavior is that the callbacks are matched over the string representations. Do you have a suggestion as to how we would rewrite that part?

I am personally considering if the `CommandManager` struct should have `Arc`'s to the three Spotify structs, but if we can avoid that it'd be great. Another option is to have a single callback created and stored in the `register_all` call - the callback can then do a match. This shouldn't be too bad of an overhead because we're using enums.

**Comment by hrkfdn** [comment]
Great work, thank you!

I think using `Option<T>` for the `Move` and `Shift` commands is okay. It may be a bit cumbersome, but it's cleaner than hardcoding them and more flexible when we need to parse the commands from binding configurations at some point.

The callback variant is fine. I don't think overhead is a problem here, as the commands are only processed on user interaction, which doesn't happen often enough for it to cause a worrying overhead, especially since we would we using enums, as you said.

On the other hand, if keeping `Arcs` simplifies things greatly, feel free to do it. They're more like global objects anyway.

**Comment by Herbstein** [comment]
I decided to go with the `Arc`s. It becomes a much cleaner implementation and it reduces the amount of references to the structs. 

The last thing missing is a parser for the commandline. It shouldn't be too hard to get something implemented there too so I'll get that done.

**Comment by Herbstein** [comment]
I just looked at it a bit more, and I'm wondering if we even keep the string-based keybinds? The parsing functions are great for parsing external files, but since both the `Event` enum and the `Key` enum are hashable we could simply put those enums into the `HashMap` instead of moving back and forth from strings.

**Comment by Herbstein** [comment]
I did some smoke testing, and it looks like the command parser is working as expected.

**Comment by Herbstein** [comment]
Any entered command that isn't correct is just silently ignored atm. The goal should be to print out "unknown command" as previous, so let's look into that next?

**Comment by hrkfdn** [comment]
That's not a hard requirement :) We can take care of that in-tree, as well.

**Comment by Herbstein** [comment]
Then I think this might be done.

**Pull request merged**
