### PR TITLE
Add hjkl controls for AddToPlaylistMenu

### LINKED ISSUE #334: cannot navigate with vim keybinds in "Add to playlist" menu
I noticed that I can navigate with hjkl everywhere but in the "Add to playlist" menu. Running ncspot 0.2.4.

### PR DESCRIPTION
**Pull request by JojiiOfficial**
Fixes #334

### CODE REVIEW

**Comment by hrkfdn** [comment]
Thanks! I just tested this but it seems to be clashing with cursive's autojump feature on my machine. Are you not experiencing this? For instance, when I repeatedly press `l` in the `AddToPlaylistMenu` it will jump between the playlists starting with "l".

**Comment by JojiiOfficial** [comment]
I probably don't have enough playlists to experience a collision there. Whats the best approach for fixing this? Disabling one of both features?

**Comment by hrkfdn** [comment]
I guess so, the question is which? 😄 I suppose the Vim users would like their bindings but I like the autojump feature quite a lot, especially if users have a lot of playlists. Thoughts anyone?

**Comment by JojiiOfficial** [comment]
An option would be to allow the user to choose which one. I'm a vim user so I prefer the vim keybindings but I'm sure there are many people not being that much into vim. Maybe a config option `keystile` or `bindingstyle` which can be set to either `vim` or `autojump`? That would make it a bit confusing since its a bit of vim either way. Probably a proper trait implementation for autojump/vim bindings would be more clean but I don't know by heart how easy that'd be.

Why does the vim keybindings don't interfere with the context menu though?

**Comment by Bettehem** [comment]
I have an idea. What if it would work by default with normal vim bindings and then by pressing `/` to enter search/find mode and then pressing `l` or `j` etc. would jump to playlists starting with that letter. This could possibly be implemented in any dialog/popup window so if you quickly want to jump to a specific option in the menu, you'd just need to press `/` and then the letter the option begins with.
So for example if you want to jump to "Add to playlist" in a dialog menu just press `/` followed by `a`
What do you think of this?

**Comment by invakid404** [comment]
The idea @Bettehem gave sounds really reasonable to me.

**Comment by hrkfdn** [comment]
I have disabled autojump for now in favor of this PR. Autojump is not documented and key bindings should definitely be supported in the context menu. If a playlist search function or similar within the context menu is required it can still be implemented separately.

Thanks for the PR @JojiiOfficial.

**Comment by BachoSeven** [comment]
@hrkfdn I just updated to `master`, but I can't confirm that the issue is solved.

Pressing `j` while in the "Add to Playlist" context still cycles through the playlists whose name starts with `j` via autojump. 

`ncspot -V` gives 0.2.5

**Comment by hrkfdn** [comment]
Mhh, odd. Can't really reproduce this. I have playlists starting with `J` and `K` but the selection moves down/up here.

**Comment by Bettehem** [comment]
I can't reproduce the problem either. For me it works as it should, going down with `j` and up with `k`

**Comment by BachoSeven** [comment]
Oh ok. I'll try to recompile it, maybe something went wrong while updating

**Comment by BachoSeven** [comment]
I forgot to report it, but I still experience the issue, even on `0.4.0`.

**Pull request merged**
