### PR TITLE
Enable wayland clipboard support by default on supported platforms

### PR DESCRIPTION
**Pull request by Bettehem**
Hi, I attempted to solve #830. This should now automatically build the wayland_clipboard clipboard feature on supported platforms.
\
\
\
I noticed right after pushing this branch that I included commits from my other PR here too, but I reverted those, so it should be fine now.

### CODE REVIEW

**Comment by hrkfdn** [comment]
Hey, thanks for the PR. Generally I'm not against enabling Wayland clipboard support by default, but I'll have to check how this affects the *BSDs, as they would fall under `unix` but don't use Wayland.

**Comment by Bettehem** [comment]
Wayland should work on the BSDs too:
https://docs.freebsd.org/en/books/handbook/x11/#x-wayland
https://en.wikipedia.org/wiki/Wayland_(display_server_protocol)

**Comment by hrkfdn** [comment]
> Wayland should work on the BSDs too: https://docs.freebsd.org/en/books/handbook/x11/#x-wayland https://en.wikipedia.org/wiki/Wayland_(display_server_protocol)

Unfortunately for OpenBSD and NetBSD that is not the case. I also don't know how many FreeBSD users use Wayland these days, as I believe it's still somewhat experimental. But I haven't used FreeBSD in a while.

**Comment by Bettehem** [comment]
I found this article of wayland running on NetBSD too so apparently it can work: https://blog.netbsd.org/tnf/entry/wayland_on_netbsd_trials_and

But I have now made changes so that the wayland clipboard feature is only built by default on linux, as the wayland support in the BSDs doesn't seem to be official.

**Comment by hrkfdn** [comment]
Thanks! Let's get it in! :)

**Comment by hrkfdn** [comment]
I just wanted to share a link on GNOME and it seems the Wayland clipboard protocol implementation used by the `wl-clipboard-rs` crate [does not support GNOME](https://github.com/YaLTeR/wl-clipboard-rs/issues/8) :( 

Is there another crate that we can use for this will support GNOME and the wlroots-based compositors?

**Comment by Bettehem** [comment]
Oh, interesting... I looked into this, and it seems to be the best course of action to default to the x11 clipboard if gnome is detected. Then it works as expected. I made a pull request which fixes the issues on gnome: #912

**Pull request merged**
