### PR TITLE
Improve context menus to make the UX/UI more consistent

### PR DESCRIPTION
**Pull request by ThomasFrans**
I'm trying to improve the context menus for all the items, to make the context menu experience more consistent with what's already offered for tracks. This PR is related to #922 and isn't finished yet.

### CODE REVIEW

**Comment by ThomasFrans** [comment]
Right now the context menus contain all the stuff they need to contain to be consistent with the Track context menus. If more stuff would need to be changed or options need to be altered/removed, I'd be happy to make changes.

**Comment by hrkfdn** [comment]
Hey @ThomasFrans, looks pretty good so far! Also don't mind moving up the play actions to the main menu.

**Comment by ThomasFrans** [comment]
Thanks! I'll move the playback stuff into the main menu then and delete the unused function. I can do this in two weeks (I don't have my laptop on me right now). I hope that's ok.

**Comment by hrkfdn** [comment]
> I hope that's ok.

Sure, this is all voluntary :)

**Comment by hrkfdn** [comment]
@ThomasFrans Sorry, completely missed that you already finished working on this. Merging it now, thanks again.

**Pull request merged**
