### PR TITLE
Expose gapless playback config option

### PR DESCRIPTION
**Pull request by Qluxzz**

### CODE REVIEW

**Comment by hrkfdn** [comment]
Thanks for the PR. Have you tested this? I don't know if this works as ncspot does not use the SPIRC/Spotify remote player that is used in librespot/spotifyd, as ncspot has its own queue.

**Comment by Qluxzz** [comment]
Yes, I have tested it with Pink Floyds The Dark Side of the Moon since it has tracks that blends together and it worked great, no more silence between tracks!

**Comment by hrkfdn** [comment]
Cool, thanks for confirming!

**Comment by deed02392** [comment]
Wow, this works really well. We might want to consider this default enabled.

**Pull request merged**
